---
- name: format disk
  become: true
  hosts: localhost
  tasks:
  - name: get disk structure
    become: true
    command: fdisk -l
    register: get_disk
  - name: get device 
    vars:
        device: "{{ get_disk.stdout | get_device }}"   
    shell: echo {{ item }}
    loop: "{{ device }}"
      
    
